### ISSUE TITLE
Fix the warnings

### ISSUE THREAD

**Issue by mnpenner** [apollographql/frontpage-server#88]
I'm trying to copy this repo as an example of how to get started with a GraphQL server, but it seems to have a bunch of warnings out of the box.

In particular, this:

```js
new SubscriptionServer(
    { subscriptionManager },
    websocketServer
);
```

Causes this:

```
TypeError: `port` or a `server` must be provided
    at new WebSocketServer (/home/mpenner/Projects/redspider-graphql/node_modules/ws/lib/WebSocketServer.js:44:11)
    at new SubscriptionServer (/home/mpenner/Projects/redspider-graphql/node_modules/subscriptions-transport-ws/dist/server.js:18:25)
    at Object.<anonymous> (/home/mpenner/Projects/redspider-graphql/server.js:48:1)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.nodeDevHook [as .js] (/home/mpenner/Projects/redspider-graphql/node_modules/node-dev/lib/hook.js:61:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
```

I'm also seeing this:

> Warning - the `printer` exports from `graphql-tag` will be removed in the next major version.

But I don't have a stack trace for that, and I haven't used `graphql-tag` anywhere explicitly.

**Comment by acomito** [comment]
```
new SubscriptionServer(
    { subscriptionManager },
    { server: websocketServer }
);
```
